name: Richard Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script: |
            cd /home/richard/portfolio-richard
            git fetch origin
            git checkout production
            git pull
            docker build -t portfolio .
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            docker run -d --name portfolio-container -p 4000:3000 portfolio
